# Generated by Django 2.2.6 on 2019-10-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_deleted',
            new_name='is_active',
        ),
    ]
